[workspace]
members = [
    "ports/cef",
    "ports/geckolib",
    "ports/servo",
]

[profile.dev]
codegen-units = 4

[profile.release]
opt-level = 3
# Uncomment to profile on Linux:
# debug = true
# lto = false

[replace]
"offscreen_gl_context:0.8.4" = { path = "/home/mortimer/Projects/rust-offscreen-rendering-context" }
"rust-webvr:0.2.0" = { path = "/home/mortimer/Projects/rust-webvr" }
#"servo-fontconfig-sys:4.0.2" = { path = "/home/mortimer/Projects/libfontconfig" }
#"html5ever:0.14.1" = { path = "/home/mortimer/Projects/html5ever" }
#"https://github.com/servo/angle#0.2.0" = { path = "/home/mortimer/Projects/angle" }
"servo-glutin:0.10.0" = { path = "/home/mortimer/Projects/glutin" }
"https://github.com/servo/webrender#0.26.0" = { path = '/home/mortimer/Projects/webrender/webrender/' }
"https://github.com/servo/webrender#webrender_traits:0.27.0" = { path = '/home/mortimer/Projects/webrender/webrender_traits' }
